version: '3.8'

services:
  nestjs_real_estate_postgres:
    image: postgres:alpine
    container_name: nestjs_real_estate_postgres
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_NAME}
    ports:
      - '5432:5432'
    volumes:
      - nestjs_real_estate_postgres_data:/var/lib/postgresql/data

  nestjs_real_estate_redis:
    image: redis:alpine
    container_name: nestjs_real_estate_redis
    ports:
      - '6379:6379'
    volumes:
      - nestjs_real_estate_redis_data:/data # Needs updating

networks:
  default:
    name: nestjs_real_estate # Needs updating

volumes:
  nestjs_real_estate_postgres_data: # Needs updating
  nestjs_real_estate_redis_data: # Needs updating
